//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorcasClub
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class Adherent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adherent()
        {
            this.Ordonnance = new HashSet<Ordonnance>();
        }
    
        public int idAdherent { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        [StringLength(30)]
        [Index("Ix_CIN", Order = 1, IsUnique = true)]
        [Remote("IsCINExist", "Adherents", AdditionalFields = "Id", ErrorMessage = "CIN existe déjà !")]
        public string CIN { get; set; }
        [StringLength(30)]
        [Index("Ix_Email1", Order = 1, IsUnique = true)]
        [Remote("IsEmail1Exist", "Adherents", AdditionalFields = "Id", ErrorMessage = "Email 1 existe déjà !")]
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        [StringLength(30)]
        [Index("Ix_Tel1", Order = 1, IsUnique = true)]
        [Remote("IsTel1Exist", "Adherents", AdditionalFields = "Id", ErrorMessage = "Tel 1 existe déjà !")]
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Adresse { get; set; }
        public string Ville { get; set; }
        public string Pays { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public string FileName { get; set; }
        public string imagephysique { get; set; }
        public byte[] Image { get; set; }
        public string Genre { get; set; }
        public string Poids { get; set; }
        public string Taille { get; set; }
        public Nullable<System.DateTime> DateNaissance { get; set; }
        public string Type { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordonnance> Ordonnance { get; set; }
    }
}
