//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorcasClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coach()
        {
            this.PreventiveIntervention = new HashSet<PreventiveIntervention>();
            this.Session = new HashSet<Session>();
        }
    
        public int idCoach { get; set; }
        public string FirstName { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> start_Date { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateBirdh { get; set; }
        public string Adresse { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string Email { get; set; }
        public byte[] imageelement { get; set; }
        public string FileName { get; set; }
        public string imagephysique { get; set; }
        public string SelectedMachine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreventiveIntervention> PreventiveIntervention { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Session> Session { get; set; }
    }
}
