//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorcasClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfigMenu
    {
        public int IdMenu { get; set; }
        public string LibelleMenu { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string IdParent { get; set; }
        public string IdChild { get; set; }
    }
}
