//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorcasClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Elements()
        {
            this.Price1 = new HashSet<Price>();
        }
    
        public int idElement { get; set; }
        public string nameElement { get; set; }
        public decimal Energie { get; set; }
        public decimal Kj { get; set; }
        public decimal Glucide { get; set; }
        public decimal Proteine { get; set; }
        public System.DateTime insertionDate { get; set; }
        public decimal price { get; set; }
        public string description { get; set; }
        public decimal weightUnity { get; set; }
        public decimal Lipide { get; set; }
        public byte[] imageElement { get; set; }
        public string FileName { get; set; }
        public string imagephysique { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Price> Price1 { get; set; }
    }
}
