//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorcasClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Memberships
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Memberships()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int idMembers { get; set; }
        public string name_Members { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string adress_Members { get; set; }
        public string CIN_Members { get; set; }
        public string membershipType { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Duree { get; set; }
        public Nullable<System.DateTime> DateDu { get; set; }
        public Nullable<System.DateTime> DateAu { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public string Email { get; set; }
        public byte[] imageelement { get; set; }
        public string FileName { get; set; }
        public string imagephysique { get; set; }
        public Nullable<decimal> Wieght { get; set; }
        public Nullable<decimal> Taille { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
