//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorcasClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int idPayment { get; set; }
        public Nullable<System.DateTime> dateEcheance { get; set; }
        public Nullable<System.DateTime> dateReception { get; set; }
        public Nullable<decimal> montant { get; set; }
        public int idReservation { get; set; }
        public int idModePayment { get; set; }
        public string etatPaiement { get; set; }
        public string Devise { get; set; }
        public string Createur { get; set; }
    
        public virtual ModePayement ModePayement { get; set; }
        public virtual Reservation Reservation { get; set; }
    }
}
