//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorcasClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreventiveIntervention
    {
        public int idIntervention { get; set; }
        public Nullable<System.DateTime> dateIntervention { get; set; }
        public string title { get; set; }
        public string Description { get; set; }
        public int Materials_idMaterials { get; set; }
        public int Materials_Coach_idCoach { get; set; }
    
        public virtual Coach Coach { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual PreventiveIntervention PreventiveIntervention1 { get; set; }
        public virtual PreventiveIntervention PreventiveIntervention2 { get; set; }
    }
}
