//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorcasClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Societe
    {
        public string CodeSociete { get; set; }
        public string CodeForme { get; set; }
        public string RaisonSociale { get; set; }
        public string Responsable { get; set; }
        public string MatriculeFiscale { get; set; }
        public string RegistreCommerce { get; set; }
        public string CodeBanque { get; set; }
        public string RibBanquaire { get; set; }
        public string Adresse { get; set; }
        public string CodePostal { get; set; }
        public string Ville { get; set; }
        public string Pays { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string FAX { get; set; }
        public string Mail { get; set; }
        public string SiteWeb { get; set; }
        public byte[] Logo { get; set; }
        public string Observation { get; set; }
        public string CodeCNAM { get; set; }
    }
}
