//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorcasClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaintenanceMachine
    {
        public int IdMaintenance { get; set; }
        public Nullable<System.DateTime> DateMaintenance { get; set; }
        public string Titre { get; set; }
        public string Description { get; set; }
        public int IdMachine { get; set; }
    
        public virtual Machine Machine { get; set; }
    }
}
