//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorcasClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordonnance
    {
        public int IdOrdonance { get; set; }
        public string NbCalorie { get; set; }
        public string NomMedecin { get; set; }
        public Nullable<System.DateTime> DateOrdonnance { get; set; }
        public int IdAdherent { get; set; }
    
        public virtual Adherent Adherent { get; set; }
    }
}
