//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorcasClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paiment
    {
        public int IdPaiment { get; set; }
        public Nullable<System.DateTime> DateEcheance { get; set; }
        public Nullable<System.DateTime> DateReception { get; set; }
        public Nullable<decimal> Montant { get; set; }
        public string EtatPaiement { get; set; }
        public string Devise { get; set; }
        public string Createur { get; set; }
        public int IdReservation { get; set; }
        public int IdModePaiment { get; set; }
    
        public virtual ModePaiement ModePaiement { get; set; }
    }
}
