//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DorcasClub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Session()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int IdSession { get; set; }
        public string Etat { get; set; }
        public System.TimeSpan HeureDebut { get; set; }
        public System.TimeSpan HeureFin { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string Createur { get; set; }
        public decimal Prix { get; set; }
        public System.DateTime DateSession { get; set; }
        public string Dure { get; set; }
        public int IdEntreneur { get; set; }
        public int IdMaChine { get; set; }
    
        public virtual Entreneur Entreneur { get; set; }
        public virtual Machine Machine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
